### ISSUE TITLE
Dreambooth and working with new tokens

### ISSUE THREAD

**Issue by VladAndronik** [AttendAndExcite/Attend-and-Excite#19]
Hi, @AttendAndExcite I am trying to use your method with finetuned model but it seems to struggle working, results with and without your method are the same. Metrics logs are not changing iteration to iteration.
Model works fine on your examples from the notebook, losses are changing and the results as well.
The only problem I can see is that the tokenizer do not know about the new words for finetuned dreambooth. For example, I am using token word "polevakatyaaa" and it decomposes it into ['pole', 'vak', 'at', 'yaa']. I select all the indices with the word, but it seems to have no clue. What can I do?

**Comment by AttendAndExcite** [comment]
Hi @VladAndronik, thanks for your interest! 
I’m not sure I understand exactly. When you use your learned token (just “an image of a polevakatyaaa” do you get your concept? Did you fine tune the model such that polevakatyaaa should be a single token?

**Comment by VladAndronik** [comment]
Yes, when I am using learned token, I get the needed result. No, I did not train the model to have it as a single token.

I have a finetuned model with two identities and two unique tokens for them. When I generate them separately, I get the needed result. But when generated simultaneously - they are mixed up or one identity dominates (common problem when finetune with two people). I tried using your method to better separate them, but it seems to have no effect when using prompt (a photo of <token1> and <token2>). I select all the tokens like in an example above polevakatyaaa => ['pole', 'vak', 'at', 'yaa']. But losses are not changing and result with and without your method are the same. So, I wanted to know, if there is anything I can do to get a better result?

**Comment by AttendAndExcite** [comment]
@VladAndronik thanks for clarifying. As stated in the paper, when a word is split to multiple tokens, the attention values are often dominated by one of the tokens. You can input the text “an image of <word>” for example to identify the dominant token to strengthen.
Additionally, please note that this combination could reside out of distribution and it is possible that SD will not be able to generate your combination.

**Comment by VladAndronik** [comment]
How would I know the dominant token? Trying different parts of the token, till I find the one which is most effective? 

Is it possible to somehow collapse all the embeddings into one for the token word? So that it can be optimized more effectively?

**Comment by VladAndronik** [comment]
Thanks, tried this, two tokens are with more attention values that the others, tried them separately and together. Unfortunately, results are the same, though the losses change a bit. If I try to generate a photo of vak (token with largest attention from polevakatyaa) => I receive some other identity. Did you experiment with other ways to add attention for multi-token words?

**Comment by AttendAndExcite** [comment]
We did not explore any other options to optimize a word with more than one token unfortunately. Sounds like it’s an expressiveness issue.
please note that strengthening the dominant token is not equivalent to just generating the dominant token (text encoder apply context to each token).

**Comment by VladAndronik** [comment]
Understood, thank you for your help and work @AttendAndExcite !
