### ISSUE TITLE
link to arxiv on project page is not working

### ISSUE THREAD

**Issue by johnowhitaker** [AttendAndExcite/Attend-and-Excite#2]
Your arxiv link on https://attendandexcite.github.io/Attend-and-Excite/ points to the project page, and should probably be switched to point to https://arxiv.org/abs/2301.13826 instead.

While I'm here: great project! It's really neat that just adding a guidance loss to force the latents to attend to all objects works so well. Love it :)

**Comment by AttendAndExcite** [comment]
Hi @johnowhitaker, thanks for your interest and kind words!
Issue fixed :)
