### ISSUE TITLE
Can this be used with the automatic1111 webui?

### ISSUE THREAD

**Issue by ImBadAtNames2019** [AttendAndExcite/Attend-and-Excite#20]
Can this be used with the automatic1111 webui?

**Comment by AttendAndExcite** [comment]
Hi @ImBadAtNames2019, thanks for your interest!
I see that there’s an [issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7585) open for integration of our method, shouldn’t be too hard to implement.
Also, if it helps, Attend and Excite is now a part of the [diffusers library](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py).

**Comment by ImBadAtNames2019** [comment]
Well i have no idea how to implement it, i tought it was already compatible. I feel like this has a lot of potential, but the fact that it cannot be used with the webui kinda kills it. Also i have no idea what the diffusers library is supposed to do.

**Comment by Natotela** [comment]
I'm also a bit perplexed by the vast lines of code in the Diffusers page.
Is the entire work routine of diffusers a CLI / code editing method?

in GUI we trust

**Comment by AttendAndExcite** [comment]
Hi all, thanks for your interest.
There's a GUI interface [in this Hugging Face space](https://huggingface.co/spaces/AttendAndExcite/Attend-and-Excite).

**Comment by galfaroth** [comment]
hey, the automatic111 makes it so easy to install extensions to their gui. I think it would be neat if you could implement support there because then, thousands of people would be using that.
