### ISSUE TITLE
How about global properties?

### ISSUE THREAD

**Issue by KIMGEONUNG** [AttendAndExcite/Attend-and-Excite#25]
Hi, Thank you for your amazing work, and I have a question about your research, not code.

The paper focused on object-centric words such as elephant or crown.
However, words indicating the global property, e.g., "at night", are also frequently omitted in the ouputs of T2I diffusion models. So, I just wonder whether your method also works to the words representing global property.
If not, I also want to know your opinion for that reasons.

Thank you.

**Comment by AttendAndExcite** [comment]
Hi @KIMGEONUNG, thanks for your interest!
In the paper, we present some examples with  global properties such as “a Picasso painting in a garden” and “A cat and a dog reading in a library” so the method works on background subjects as well. I hope this answers your question.

**Comment by AttendAndExcite** [comment]
Here’s an example I got with a random seed for “a cat and a dog at night”:
![6E5DAE64-D5E7-4044-81A1-F7BE2AEF5C1A](https://user-images.githubusercontent.com/122183458/225750295-f5f1dbe8-2463-4c39-b83f-ca648e56508a.png)
