### ISSUE TITLE
How do I give the token indices if I want to emphasize a group of words?

### ISSUE THREAD

**Issue by himmetozcan** [AttendAndExcite/Attend-and-Excite#27]
My prompt is "a blue stone and red flowers". If I want to emphasize "red flowers" together what should be the indices, [5, 6] ?

**Comment by AttendAndExcite** [comment]
Hi @himmetozcan, thanks for your interest!
As mentioned in the paper, the attribute bindings are strengthened as a side effect of strengthening the subject so in this case, you would need to strengthen flowers (should be index 6 if I’m not mistaken).

**Comment by himmetozcan** [comment]
Thanks for the fast reply.
