### ISSUE TITLE
How to save the attention maps

### ISSUE THREAD

**Issue by rulixiang** [AttendAndExcite/Attend-and-Excite#3]
Hey, this is an very interesting work! 
I tried to save the cross-attention maps by setting `save_cross_attention_maps` in `config.py` to `True`, but sadly found no attention map was saved. Can you show how to save the attention maps?
Thanks!

**Comment by AttendAndExcite** [comment]
Hi @rulixiang, thanks for your interest!
This configuration is currently not supported in the code, however, you can use our [cross-attention visualization notebook](https://github.com/AttendAndExcite/Attend-and-Excite/blob/main/notebooks/explain.ipynb) to visualize the cross-attention maps obtained with and without Attend-and-Excite.

**Comment by rulixiang** [comment]
Thanks, I found it!
