### ISSUE TITLE
Compatibility with latest Diffusers versions

### ISSUE THREAD

**Issue by ExponentialML** [AttendAndExcite/Attend-and-Excite#8]
Hello, thanks for your great work! 

Currently, this repository is built off of a Diffusers version from [September 8th, 2022](https://github.com/huggingface/diffusers/commit/3f55d1359fb7b93070d87c2afe9c453668249d45). This breaks compatibility with other implementations when building custom scripts. It would be much appreciated if this repository was upgraded to support the new CrossAttention modules on current versions of Diffusers.

**Comment by AttendAndExcite** [comment]
Hi @ExponentialML, thanks for the interest!
This is definitely prioritized high on our todo list. The task of adapting to the new cross attention layer is not trivial, I think there’s also an open issue on diffusers to implement our method, hopefully this will be resolved soon.

**Comment by ArielReplicate** [comment]
I'm also having trpuble with diffusers version.

When trying to work with the version suggested by requirements.txt

I get:
```
Traceback (most recent call last):
  File "run.py", line 89, in <module>
    main()
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "run.py", line 64, in main
    stable = load_model(config)
  File "run.py", line 19, in load_model
    stable = AttendAndExcitePipeline.from_pretrained("CompVis/stable-diffusion-v1-4").to(device)
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/diffusers/pipeline_utils.py", line 373, in from_pretrained
    load_method = getattr(class_obj, load_method_name)
TypeError: getattr(): attribute name must be string
```

**Comment by AttendAndExcite** [comment]
Hi @ArielReplicate, are you sure you downloaded all the packages with the versions specified in the requirements file?

**Comment by evinpinar** [comment]
I've added compatibility to latest diffuser versions, please check here: https://github.com/evinpinar/Attend-and-Excite-diffusers

**Comment by Advaya24** [comment]
@evinpinar Thank you for the module! What is the expected runtime for this?

**Comment by evinpinar** [comment]
Runtime is a matter of seconds on a single 12GB 2080 ti. I've provided implementation with half-precision to be able to fit into this GPU. I'm not sure how long it would take on an M2.

**Comment by AttendAndExcite** [comment]
PR merged!
